# id generated by capnp
@0xd03239fac694d7b3;

using Powerbox = import "/sandstorm/powerbox.capnp";
using ApiSession = import "/sandstorm/api-session.capnp".ApiSession;

const apiTagValue :ApiSession.PowerboxTag = (
  canonicalUrl = "https://app-index.sandstorm.io",
);

const appIndexDescriptor :Powerbox.PowerboxDescriptor = (
  tags = [
    (id = 0xc879e379c625cdc7, value = .apiTagValue)
  ],
);
