

export const Manifest = {
  sources: [
    {
      name: 'Primary App Index',
      baseUrl: "https://app-index.sandstorm.io",
      apps: [
        /*
        {name: 'Simple Todos'},
        {name: 'Roundcube'},
        {name: 'Swagger Editor'},
        {name: 'EtherDraw'},
        {name: 'Apache Wave'},
        {name: 'Laverna'},
        {name: 'Hummingbird'},
        {name: 'Telescope Nova'},
        {name: 'Kiwix'},
        {name: 'ShareLaTeX'},
        {name: 'Mercurial'},
        {name: 'Yet Another TODO'},
        {name: 'GitWeb'},
        {name: 'MediaGoblin'},
        {name: 'Meteor Blocks'},
        {name: 'Acronymy'},
        {name: 'Hacker Slides'},
        {name: 'Baby Buddy'},
        {name: 'Davros'},
        {name: 'Legends Browser'},
        {name: 'Radicale'},
        {name: 'HLedger Web'},
        */
        {name: 'SandMD'},
/*
        {name: 'EtherCalc'},
        {name: 'WordPress'},
        {name: 'Game of Y'},
        {name: 'Annotate'},
        {name: 'Biandang'},
        {name: 'OwnTracks'},
        {name: 'dieStorm'},
        {name: 'Angr Binary Reverse-Engineering'},
        {name: 'Gogs'},
        {name: 'Idea Otter'},
        {name: 'SandCal'},
        {name: 'BrowserQuest'},
        {name: 'Dillinger'},
        {name: 'Etherpad'},
        {name: 'Hugo'},
        {name: 'Wekan'},
        {name: 'CrypTag'},
        {name: 'Ghost'},
        {name: 'Simple Rich Text Editor'},
        {name: 'TextEditor'},
        {name: 'CodiMD'},
        {name: 'draw.io'},
        {name: 'FileDrop'},
        {name: 'Hacker CMS'},
        {name: 'Doku Wiki'},
        {name: 'SandChat'},
        {name: "Let's Chat"},
        {name: 'Go'},
        {name: 'Hacker Resume'},
        {name: 'IPython Notebook'},
        {name: 'Sandpass'},
        {name: 'Framadate'},
        {name: 'Collections'},
        {name: 'Contact Otter'},
        {name: 'Brainstorm'},
        {name: 'Permanote'},
        {name: 'Giftr'},
        {name: 'Neuron Catalog'},
        {name: 'Linksholder'},
        {name: 'Firefly III'},
        {name: 'Rocket.Chat'},
        {name: 'Paperwork'},
        {name: 'Scrumblr'},
        {name: 'Groove Basin'},
        {name: 'Quick Survey'},
        {name: 'Monica'},
        {name: 'Piwik Web Analytics'},
        {name: 'MediaWiki'},
        {name: 'Simple Chat'},
        {name: 'Duoludo'},
        {name: 'Lychee'},
        {name: 'Hakyll CMS'},
        {name: 'Tiny Tiny RSS'},
        {name: 'NodeBB'},
        {name: 'SandForms'},
        {name: 'GitLab'},
        */
      ],
    },
    {
      name: 'Mansia App Index',
      baseUrl: 'https://o9yg4ss2m74ujs6rahta.mansia.net',
      apps: [
        {name: 'Secrets of Toanium'},
        {name: 'Rokugan Recorder'},
      ],
    }
  ]
}
